---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: istio-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: github-auth
  url: https://github.com/TV4/k8s-istio-system
  ignore: |
    /*
    !/flux/
